### PR TITLE
Add windows support for various checks, and remove unused includes

### PR DESCRIPTION
**Pull request by helmesjo**
While packaging `libevent` I had to do some changes for everything to build correctly (note that I haven't run any unit tests yet).

The following changes were required to make it build:
* Add windows support for multiple checks.
* Don't include headers that "contain the things that the `HAVE_` check promises), it causes conflicts and also isn't useful since the users of this feature (in this case `libevent`) will include (and also be responsible to) the required headers.

### CODE REVIEW

**Comment by boris-kolpackov** [comment]
Ok, I've manually merged this into the new `libevent-checks2` branch (and deleted `libevent-checks`) but I dropped some changes (see below). But first, I find myself spending an increasing amount of time untangling and cleaning up your changes so can we please have a couple of "house rules" going forward:

1. Don't bundle unrelated changes into single PR. For example, this PR contains two commits and it should have been two separate PRs.

2. Please try to be consistent with commit messages, currently they are all over the place and I have to re-write every one of them. Check the history in the `libevent-checks2` branch and try to follow this style.

3. Please try to include some rationale in comments for the less obvious changes that you make. For example, I had to add explanatory comments in both of the commits in this PR; please check the  `libevent-checks2` branch to get the idea.

Overall, I think we need to slow down a bit and pay a bit more attention to the correctness and quality of the changes. I understand that you want to package the libraries that you need ASAP but `libbuild2-autoconf` and the checks it contains is a foundation to many packages (both existing and future) and we need to make sure it is solid.

Ok, now regarding this PR specifically:

> Don't include headers that "contain the things that the HAVE_ check promises), it causes conflicts and also isn't useful since the users of this feature (in this case libevent) will include (and also be responsible to) the required headers.

This doesn't make sense to me and I've dropped this change. While this may help `libevent`, I don't think this is a generally applicable semantics since that means the user of the check will need to re-create the same preprocessor decision tree in order to include an appropriate header. This is both burdensome and error-prone (e.g., the two decision trees can get out of sync).

Also, normally, including a system header should be idempotent so it's strange you see conflicts. I think the only sensible change on the `libbuild2-autoconf` side to resolve this would be to include different headers if the ones we are currently including are for some reason not idempotent.

**Comment by boris-kolpackov** [comment]
> Also, normally, including a system header should be idempotent so it's strange you see conflicts.

Ok, I think I may have figured out what could be the issue and committed a fix (see the comments for details): https://github.com/build2/libbuild2-autoconf/commit/04b6d354b1caa3945b0129021adb776c32d04256

**Comment by helmesjo** [comment]
> **I find myself spending an increasing amount of time untangling and cleaning up your changes**

Seems rather loaded. I looked through these supposed cleanups in the history and fail to see a huge difference outside of what I'd label as personal preference (which is totally fine, but please provide this feedback after 1-3 PRs, not, you know, 20).

> **1. Don't bundle unrelated changes into single PR. For example, this PR contains two commits and it should have been two separate PRs.**

No problem! And I assume you're not suggesting this has been a recurring problem? Given that my 20-some PRs have been highly atomic changes in the form of "Add check X". But for sure, I feel the same about PRs anyways.

> **2. Please try to be consistent with commit messages, currently they are all over the place and I have to re-write every one of them. Check the history in the `libevent-checks2` branch and try to follow this style.**

Hmm... Gotta say, I'm (once again) a bit surprised with the choice of words here... "currently all over the place", "I have to re-write every one of them". For the sake of it I went through a handful of my PRs, and _basically all of them_ followed this format:
image
As mentioned, I made ~23 PRs in a matter of days (also first PRs for any build2 related product), so I'm also sure one can notice inconsistencies.

Now if you don't like that it's totally fine, but try to focus on that then. Or if it's some other commit message you think of in particular, please be more specific. I've looked through the commit history of this repo but can't say any sort of format is overly obvious, but it's all subjective of course.

> 3. **Please try to include some rationale in comments for the less obvious changes that you make. For example, I had to add explanatory comments in both of the commits in this PR; please check the  `libevent-checks2` branch to get the idea.**

Are we talking commit-message or in-code comments? I assume the latter..? Sure, makes sense (though again not sure which one was the culprit in this case).


Anyways, feedback is never wrong & thanks for taking your time to look through all these additions I made (and get them in rather quickly), it eases the process of packaging the libraries that are currently on the way.

**Comment by helmesjo** [comment]
> Ok, now regarding this PR specifically:
> 
> > **Don't include headers that "contain the things that the HAVE_ check promises), it causes conflicts and also isn't useful since the users of this feature (in this case libevent) will include (and also be responsible to) the required headers.**
> 
> This doesn't make sense to me and I've dropped this change. While this may help `libevent`, I don't think this is a generally applicable semantics since that means the user of the check will need to re-create the same preprocessor decision tree in order to include an appropriate header. This is both burdensome and error-prone (e.g., the two decision trees can get out of sync).
> 
> Also, normally, including a system header should be idempotent so it's strange you see conflicts. I think the only sensible change on the `libbuild2-autoconf` side to resolve this would be to include different headers if the ones we are currently including are for some reason not idempotent.

Wouldn't this make perfect sense though? Yes, a library would be checking if the platform/compiler in question supports what it needs, but unless it's some built in keyword then it also _always_ need to include some header to get this functionality (unless it's a built in keyword). Doing this "automagically" for the library does not seem like a solid approach IMO (and evidently doesn't work for `libevent`). So I strongly disagree that these things (eg. defines like `socklen_t` which is made available by the `<ws2tcpip.h>` header on windows) should be implicitly included. Just take one look in that file (probably most Win32 headers) and you'll see that it has _LOADS_ of `#ifdef` checks that will alter behavior depending on user-specified `#define`s and order of includes.

My point being, when doing it the way it is now (implicit includes to bring in typedefs etc), it _does_ change behavior in libraries. It may be that this is (generally) only a Windows-only issue, but the reasoning is the same for all platforms (it is an inherent problem with includes). Libraries include what they use.

**Comment by boris-kolpackov** [comment]
[I will comment on the procedural points later focusing on the technical stuff so that we can make progress.]

> Yes, a library would be checking if the platform/compiler in question supports what it needs using a `HAVE_XXX` check like these, but unless it's some built in keyword then it also always need to include some header to get this functionality.

Yes, I completely agree about the `HAVE_*` checks but this is not `HAVE_SOCKLEN_T`, this is `socklen_t`, which has the semantics of "get me the `socklen_t` definition depending on the platform".

**Comment by boris-kolpackov** [comment]
A few comments on the procedural points:

> Seems rather loaded. I looked through these supposed cleanups in the history and fail to see a huge difference outside of what I'd label as personal preference (which is totally fine, but please provide this feedback after 1-3 PRs, not, you know, 20).

Ok, fair enough.

> No problem! And I assume you're not suggesting this has been a recurring problem? Given that my 20-some PRs have been highly atomic changes in the form of "Add check X".

Yes, this is about this specific PR. I had to jump through some hoops to keep one commit and drop the other.

> Hmm... Gotta say, I'm (once again) a bit surprised with the choice of words here... "currently all over the place", "I have to re-write every one of them". For the sake of it I went through a handful of my PRs, and basically all of them followed this format:

What triggered me is the commit in this PR with the subject line "The following are all supported on windows:" which I think goes against all "good git commit subject" practices. But it's true your PR commits were fairly consistent and I am probably reacting to all the PRs which were not all by you and which had quite a bit of variability.

Overall, sorry if this came off as loaded, I guess I felt a bit frustrated spending my Sun on this.

**Pull request merged**
